 et:
    # Dilepton Quantities
    yield: "Total Yield"
    m_vis:  et:
    # Dilepton Quantities
    yield: "Total Yield"
    m_vis: "Visible di-#tau mass / GeV"
    pt_vis: "Visible di-#tau p_{T} / GeV"
    DiTauDeltaR: "#DeltaR(e, ^{}#tau_{h})"
    m_sv: "SVFit di-#tau mass (Puppi) / GeV"
    pt_sv: "SVFit di-#tau p_{T} (Puppi) / GeV"
    eta_sv: "SVFit di-#tau #eta (Puppi)"
    m_fastmtt: "fastMTT di-#tau mass (Puppi) / GeV"
    pt_fastmtt: "fastMTT di-#tau p_{T} (Puppi) / GeV"
    eta_fastmtt: "fastMTT di-#tau #eta (Puppi)"
    phi_fastmtt: "fastMTT di-#tau #varphi (Puppi)"
    m_sv_pf: "SVFit di-#tau mass (PF) / GeV"
    pt_sv_pf: "SVFit di-#tau p_{T} (PF) / GeV"
    eta_sv_pf: "SVFit di-#tau #eta (PF)"
    m_fastmtt_pf: "fastMTT di-#tau mass (PF) / GeV"
    pt_fastmtt_pf: "fastMTT di-#tau p_{T} (PF) / GeV"
    eta_fastmtt_pf: "fastMTT di-#tau #eta (PF)"
    pt_tt: "p_{T}(#tau#tau) (Puppi) / GeV"
    pt_tt_pf: "p_{T}(#tau#tau) (PF) / GeV"

    # Lepton quantities
    pt_1: "Electron p_{T} / GeV"
    pt_2: "Hadronic Tau p_{T} / GeV"
    eta_1: "Electron #eta"
    eta_2: "Hadronic Tau #eta"

    # Jet quantities
    jpt_1: "Leading Jet p_{T} / GeV"
    jpt_2: "Trailing Jet p_{T} / GeV"
    jeta_1: "Leading Jet #eta"
    jeta_2: "Trailing Jet #eta"
    jdeta: "#Delta #eta_{jj}"
    jphi_1: "Leading Jet #varphi"
    jphi_2: "Trailing Jet #varphi"
    mjj: "Di-Jet mass m_{jj} / GeV"
    dijetpt: "Di-Jet p_{T} / GeV"
    pt_ttjj: "p_{T}(#tau#tau + di-Jet) (PF) / GeV"
    pt_ttjj_puppi: "p_{T}(#tau#tau + di-Jet) (Puppi) / GeV"
    njets: "Number of Jets"

    # B-jet quantities
    nbtag: "Number of b-tagged Jets"
    bpt_1: "Leading b-Jet p_{T} / GeV"
    bpt_2: "Trailing b-Jet p_{T} / GeV"
    beta_1: "Leading b-Jet #eta"
    beta_2: "Trailing b-Jet #eta"

    # MET quantities
    met: "Missing transverse Energy (Puppi) / GeV"
    metphi: "Missing transverse Energy (Puppi) #varphi"
    puppimet: "Missing transverse Energy (Puppi) / GeV"
    puppimetphi: "Missing transverse Energy (Puppi) #varphi"
    pfmet: "Missing transverse Energy (PF) / GeV"
    pfmetphi: "Missing transverse Energy (PF) #varphi"

    # Lepton-MET quantities
    mt_1: "Transverse mass m_{T}(e, #slash{E}_{T}) (PF) / GeV"
    mt_2: "Transverse mass m_{T}(^{}#tau_{h}, #slash{E}_{T}) (PF) / GeV"
    mt_tot: "Total transverse mass m_{T}^{tot} (PF) / GeV"
    mTdileptonMET: "Transverse mass m_{T}(e+^{}#tau_{h}, #slash{E}_{T}) (PF) / GeV"
    pZetaMissVis: "p_{#zeta}^{miss} - 0.85 #upoint p_{#zeta}^{vis} (PF) / GeV"
    mt_1_puppi: "Transverse mass m_{T}(e, #slash{E}_{T}) (Puppi) / GeV"
    mt_2_puppi: "Transverse mass m_{T}(^{}#tau_{h}, #slash{E}_{T}) (Puppi) / GeV"
    mt_tot_puppi: "Total transverse mass m_{T}^{tot} (Puppi) / GeV"
    mTdileptonMET_puppi: "Transverse mass m_{T}(e+^{}#tau_{h}, #slash{E}_{T}) (Puppi) / GeV"
    pZetaPuppiMissVis: "p_{#zeta}^{miss} - 0.85 #upoint p_{#zeta}^{vis} (Puppi) / GeV"

    # MELA quantities
    ME_D: "MELA D^{VBF}_{Z + 2 Jets}"
    ME_vbf_vs_Z: "MELA D^{VBF}_{Z + 2 Jets}"
    ME_ggh_vs_Z: "MELA D^{ggH}_{Z + 2 Jets}"
    ME_vbf_vs_ggh: "MELA D^{VBF}_{ggH}"
    ME_ggh: "MELA ^{}P(ggH)"
    ME_vbf: "MELA ^{}P(VBF)"
    ME_z2j_1: "MELA ^{}P_{1}(Z + 2 Jets)"
    ME_z2j_2: "MELA ^{}P_{2}(Z + 2 Jets)"
    ME_q2v1: "MELA Q^{2}(^{}V_{1}) / GeV^{2}"
    ME_q2v2: "MELA Q^{2}(^{}V_{2}) / GeV^{2}"
    ME_costheta1: "MELA cos(#Theta_{1})"
    ME_costheta2: "MELA cos(#Theta_{2})"
    ME_costhetastar: "MELA cos(#Theta*)"
    ME_phi: "MELA #Phi"
    ME_phi1: "MELA #Phi_{1}"
    pt_vis: "Visible di-#tau p_{T} / GeV"
    DiTauDeltaR: "#DeltaR(e, ^{}#tau_{h})"
    m_sv: "SVFit di-#tau mass (Puppi) / GeV"
    pt_sv: "SVFit di-#tau p_{T} (Puppi) / GeV"
    eta_sv: "SVFit di-#tau #eta (Puppi)"
    m_fastmtt: "fastMTT di-#tau mass (Puppi) / GeV"
    pt_fastmtt: "fastMTT di-#tau p_{T} (Puppi) / GeV"
    eta_fastmtt: "fastMTT di-#tau #eta (Puppi)"
    phi_fastmtt: "fastMTT di-#tau #varphi (Puppi)"
    m_sv_pf: "SVFit di-#tau mass (PF) / GeV"
    pt_sv_pf: "SVFit di-#tau p_{T} (PF) / GeV"
    eta_sv_pf: "SVFit di-#tau #eta (PF)"
    m_fastmtt_pf: "fastMTT di-#tau mass (PF) / GeV"
    pt_fastmtt_pf: "fastMTT di-#tau p_{T} (PF) / GeV"
    eta_fastmtt_pf: "fastMTT di-#tau #eta (PF)"
    pt_tt: "p_{T}(#tau#tau) (Puppi) / GeV"
    pt_tt_pf: "p_{T}(#tau#tau) (PF) / GeV"

    # Lepton quantities
    pt_1: "Electron p_{T} / GeV"
    pt_2: "Hadronic Tau p_{T} / GeV"
    eta_1: "Electron #eta"
    eta_2: "Hadronic Tau #eta"

    # Jet quantities
    jpt_1: "Leading Jet p_{T} / GeV"
    jpt_2: "Trailing Jet p_{T} / GeV"
    jeta_1: "Leading Jet #eta"
    jeta_2: "Trailing Jet #eta"
    jdeta: "#Delta #eta_{jj}"
    jphi_1: "Leading Jet #varphi"
    jphi_2: "Trailing Jet #varphi"
    mjj: "Di-Jet mass m_{jj} / GeV"
    dijetpt: "Di-Jet p_{T} / GeV"
    pt_ttjj: "p_{T}(#tau#tau + di-Jet) (PF) / GeV"
    pt_ttjj_puppi: "p_{T}(#tau#tau + di-Jet) (Puppi) / GeV"
    njets: "Number of Jets"

    # B-jet quantities
    nbtag: "Number of b-tagged Jets"
    bpt_1: "Leading b-Jet p_{T} / GeV"
    bpt_2: "Trailing b-Jet p_{T} / GeV"
    beta_1: "Leading b-Jet #eta"
    beta_2: "Trailing b-Jet #eta"

    # MET quantities
    met: "Missing transverse Energy (Puppi) / GeV"
    metphi: "Missing transverse Energy (Puppi) #varphi"
    puppimet: "Missing transverse Energy (Puppi) / GeV"
    puppimetphi: "Missing transverse Energy (Puppi) #varphi"
    pfmet: "Missing transverse Energy (PF) / GeV"
    pfmetphi: "Missing transverse Energy (PF) #varphi"

    # Lepton-MET quantities
    mt_1: "Transverse mass m_{T}(e, #slash{E}_{T}) (PF) / GeV"
    mt_2: "Transverse mass m_{T}(^{}#tau_{h}, #slash{E}_{T}) (PF) / GeV"
    mt_tot: "Total transverse mass m_{T}^{tot} (PF) / GeV"
    mTdileptonMET: "Transverse mass m_{T}(e+^{}#tau_{h}, #slash{E}_{T}) (PF) / GeV"
    pZetaMissVis: "p_{#zeta}^{miss} - 0.85 #upoint p_{#zeta}^{vis} (PF) / GeV"
    mt_1_puppi: "Transverse mass m_{T}(e, #slash{E}_{T}) (Puppi) / GeV"
    mt_2_puppi: "Transverse mass m_{T}(^{}#tau_{h}, #slash{E}_{T}) (Puppi) / GeV"
    mt_tot_puppi: "Total transverse mass m_{T}^{tot} (Puppi) / GeV"
    mTdileptonMET_puppi: "Transverse mass m_{T}(e+^{}#tau_{h}, #slash{E}_{T}) (Puppi) / GeV"
    pZetaPuppiMissVis: "p_{#zeta}^{miss} - 0.85 #upoint p_{#zeta}^{vis} (Puppi) / GeV"

    # MELA quantities
    ME_D: "MELA D^{VBF}_{Z + 2 Jets}"
    ME_vbf_vs_Z: "MELA D^{VBF}_{Z + 2 Jets}"
    ME_ggh_vs_Z: "MELA D^{ggH}_{Z + 2 Jets}"
    ME_vbf_vs_ggh: "MELA D^{VBF}_{ggH}"
    ME_ggh: "MELA ^{}P(ggH)"
    ME_vbf: "MELA ^{}P(VBF)"
    ME_z2j_1: "MELA ^{}P_{1}(Z + 2 Jets)"
    ME_z2j_2: "MELA ^{}P_{2}(Z + 2 Jets)"
    ME_q2v1: "MELA Q^{2}(^{}V_{1}) / GeV^{2}"
    ME_q2v2: "MELA Q^{2}(^{}V_{2}) / GeV^{2}"
    ME_costheta1: "MELA cos(#Theta_{1})"
    ME_costheta2: "MELA cos(#Theta_{2})"
    ME_costhetastar: "MELA cos(#Theta*)"
    ME_phi: "MELA #Phi"
    ME_phi1: "MELA #Phi_{1}"