training:
 bsize_train: 1000
 bsize_val: 1000
 bsize_test: 1000
 grad_clip: 5.0
 n_epochs: 500
 use_amp: False
 s_scale_max: 5

optimizer:
 lr: 0.01

scheduler:
 step_size: 10
 gamma: 0.1
 factor: 0.1
 patience: 5
 threshold: 0.0001
 cooldown: 0
 min_lr: 0.000001
 eps: 0.00000001