device: 

training:
 bsize_train: 500
 bsize_val: 500
 bsize_test: 500
 grad_clip: 5.0
 n_epochs: 300
 use_amp: False
 s_scale_max: 1.5
model:
 n_layers: 8
 hidden_dims: 64
 s_scale: 3.0
scheduler:
 step_size: 10
 gamma: 0.1
 factor: 0.1
 patience: 5
 threshold: 0.0001
 cooldown: 0
 min_lr: 0.0000001
 eps: 0.00000001

optimizer:
 lr: 0.001
 betas: (0.9, 0.99)
 eps: 0.00000001
 weight_decay: 0.00001

save:
 save_directory: 

