event_preselection:
 eta1: (eta_1 <= 2.1),
 eta2: (eta_2 <= 2.3),
 pt1: (pt_1 >= 25),
 pt2: (pt_2 >= 30),
 tau_decaymode2: (tau_decaymode_2 == 0) || (tau_decaymode_2 == 1) || (tau_decaymode_2 == 10) || (tau_decaymode_2 == 11)

event_preselection_loose:         
 eta1: (eta_1 <= 2.1),
 eta2: (eta_2 <= 2.3),
 pt1: (pt_1 >= 23),
 pt2: (pt_2 >= 20),
 tau_decaymode2: (tau_decaymode_2 == 0) || (tau_decaymode_2 == 1) || (tau_decaymode_2 == 10) || (tau_decaymode_2 == 11)

DR:
 pt_1: (mt_1 >= 70)
 qcd_charge: (q_1 * q_2 < 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)

DR_OS:
 pt_1: (mt_1 >= 70)
 qcd_charge: (q_1 * q_2 < 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)

DR_SS:
 pt_1: (mt_1 >= 70)
 qcd_charge: (q_1 * q_2 > 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)

antiDR:
 pt_1: (mt_1 < 70)

SR:
 transverse_mass: (mt_1 <= 70),
 qcd_charge: (q_1 * q_2 < 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)
 passing_tight: (id_tau_vsJet_Tight_2 == True)

AR:
 transverse_mass: (mt_1 <= 70),
 qcd_charge: (q_1 * q_2 < 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)
 failing_tight_passing_vloose: (id_tau_vsJet_Tight_2 == False) && (id_tau_vsJet_VVLoose_2 == True)

SR_like:
 transverse_mass: (mt_1 > 70),
 qcd_charge: (q_1 * q_2 < 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)
 passing_tight: (id_tau_vsJet_Tight_2 == True)

AR_like:
 transverse_mass: (mt_1 > 70),
 qcd_charge: (q_1 * q_2 < 0),
 angular_separation: (((eta_1 - eta_2)**2 + (phi_1 - phi_2)**2)**0.5 > 0.5)
 failing_tight_passing_vloose: (id_tau_vsJet_Tight_2 == False) && (id_tau_vsJet_VVLoose_2 == True)

Njets_0:
 njets_0: (njets == 0)
Njets_1:
 njets_1: (njets == 1)
Njets_2+:
 njets_2+: (njets >= 2)